POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
  "username": "testuser2",
  "password": "test123",
  "email": "test2@gmail.com",
  "name": "test"
}

###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "test123"
}

###
GET http://localhost:9090/get_user_and_Profile HTTP/1.1
Content-Type: application/json

{
  "token": "0884b2c40db186c923d29fd13ce72f8a8fa4bf6eb716aeda702adbc0047a6e9c"
}
